# Generated by Django 5.0 on 2023-12-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregister',
            name='loogin_credential_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffregister',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
