# Generated by Django 5.0 on 2023-12-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_featurestable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturesTable',
            new_name='Features',
        ),
    ]
