# Generated by Django 5.0 on 2024-01-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_remove_patient_paid_payment_patient_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='remaining_amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='total_amount',
            field=models.FloatField(blank=True),
        ),
    ]
